# Generated by Django 5.0.4 on 2024-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
    ]
