# Generated by Django 5.0.4 on 2024-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
